config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "dashboard#index"
  resources :customers, only: [ :index ]
  resources :machines

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/customer_search_term.rb
class CustomerSearchTerm
	attr_reader :where_clause, :where_args, :order
	def initialize(search_term)
		search_term = search_term.downcase
		@where_clause = ""
		@where_args = {}
		if search_term =~ /@/
			build_for_email_search(search_term)
		else 
			build_for_name_search(search_term)
		end
	end

private 

	def build_for_name_search(search_term)
		@where_clause << case_insensative_search(:first_name)
		@where_args[:first_name] = starts_with(search_term)

		@where_clause << " OR #{case_insensative_search(:last_name)}"
		@where_args[:last_name] = starts_with(search_term)

		@order = "last_name asc"
	end

	def starts_with(search_term)
		search_term + "%"
	end

	def case_insensative_search(field_name)
		"lower(#{field_name}) like :#{field_name}"
	end

	def extract_name(email)
		email.gsub(/@.*$/,'').gsub(/[0-9]+/,'')
	end


	def build_for_email_search(search_term)
		@where_clause << case_insensitive_search(:first_name)
		@where_args[:first_name] = starts_with(extract_name(search_term))

		@where_clause << " OR #{case_insensitive_search(:last_name)}"
		@where_args[:last_name] = starts_with(extract_name(search_term))

		@where_clause << " OR #{case_insensitive_search(:email)}"
		@where_args[:email] = search_term

		@order = "lower(email) = " + ActiveRecord::Base.connection.quote(search_term) + " desc, last_name asc"
	end
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/models/machine_search_term.rb
class MachineSearchTerm
	attr_reader :where_clause, :where_args, :order
	def initialize(search_term)
		search_term = search_term.downcase
		@where_clause = ""
		@where_args = {}
		if search_term =~ /@/
			build_for_ip_search(search_term)
		else 
			build_for_machname_search(search_term)
		end
	end

private 

	def build_for_machname_search(search_term)
		@where_clause << case_insensative_search(:machine_name)
		@where_args[:machine_name] = starts_with(search_term)

		@order = "machine_name asc"
	end

	def starts_with(search_term)
		search_term + "%"
	end

	def case_insensative_search(field_name)
		"lower(#{field_name}) like :#{field_name}"
	end

	def extract_name(email)
		email.gsub(/@.*$/,'').gsub(/[0-9]+/,'')
	end


	def build_for_ip_search(search_term)
		@where_clause << case_insensitive_search(:ip_address)
		@where_args[:first_name] = starts_with(extract_name(search_term))

		@order = "lower(machine_name) = " + ActiveRecord::Base.connection.quote(search_term) + " desc, ip_address asc"
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController 
	
	PAGE_SIZE = 10

	def index 

		@page = (params[:page] || 0).to_i

		if params[:keywords].present?
			@keywords = params[:keywords]
			customer_search_term = CustomerSearchTerm.new(@keywords)
			@customers = Customer.where(customer_search_term.where_clause, customer_search_term.where_args).order(customer_search_term.order).offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
		else
			@customers = []
		end
		respond_to do |format|
			format.html {}
			format.json {
				render json: { customers: @customers }
			}


		end
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
	end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController 

	PAGE_SIZE = 10

	def index 

		@page = (params[:page] || 0).to_i

		if params[:keywords].present?
			@keywords = params[:keywords]
			machine_search_term = MachineSearchTerm.new(@keywords)
			@machines = Machine.where(machine_search_term.where_clause, machine_search_term.where_args).order(machine_search_term.order).offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
		else
			@machines = []
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_pager.html.erb
<nav>
	<ul class="pager">
	<% if page > 0 %>
		<li class="previous">
		<%= link_to "&larr; Previous".html_safe, customers_path(keywords: keywords, page: page - 1), title: "Previous Page" %>
		</li>
	<% end %>
	
		<li class="next">
		<%= link_to "Next &rarr;".html_safe, customers_path(keywords: keywords, page: page + 1), title: "Next Page" %>
		</li>
	</ul>
</nav>

app/views/customers/index.html.erb
<section>
  <shine-customer-search></shine-customer-search>
</section>
<%= javascript_pack_tag "customers" %>

<!-- PRE-ANGULAR SEARCH CODE -->

<!-- <section class="search-form">
	<%= form_for :customers, method: :get do |f| %>
		<div class="input-group input-group-lg">
			<%= label_tag :keywords, nil, class: "sr-only" %>
			<%= text_field_tag :keywords, nil, placeholder: "First Name, Last Name, or Email Address", class: "form-control input-lg" %>
				<span class="input-group-btn">
					<%= submit_tag "Find Customers", class: "btn btn-primary btn-lg" %>
				</span>
		</div>
	<% end %>
</section>

<section class="search-results">
<header>
	<h1 class="h3">Results</h1>
</header>
<% if @customers.present? %>
	<%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
<% end %>
<ol class="list-group">
	<% @customers.each do |customer| %>
		<li class="list-group-item clearfix">
			<h3 class="pull-right">
				<small class="text-uppercase">Joined</small> <%= l customer.created_at.to_date %>
			</h3>
			<h2 class="h3">
				<%= customer.first_name %> <%= customer.last_name %>
			<small><%= customer.username %></small>
		</h2>
			<h5><%= customer.email %></h5>
			
		</li>
	<% end %>
</ol>
<% if @customers.present? %>
	<%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
<% end %>
</section> -->


<!-- <section class="search-results">
<header>
	<h1 class="h3">Results</h1>
</header>
<table class="table table-striped">
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Joined</th>
		</tr>
	</thead>
<tbody>
	<% @customers.each do |customer| %>
		<tr>
			<td><%= customer.first_name %></td>
			<td><%= customer.last_name %></td>
			<td><%= customer.email %></td>
			<td><%= l customer.created_at.to_date %></td>
		</tr>
	<% end %>
</tbody>
</table>
</section> -->

app/views/dashboard/index.html.erb
<header>
	<h1>
		Welcome! <%= current_user.email %>
	</h1>
</header>
<section>
	<p>
		Devlopment Operations
	</p>
	<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netprog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag    "application" %>
    <%= stylesheet_pack_tag    "application" %>
  </head>

  <body class="container">
  	<h1>Development Operations</h1>
  	<% if notice.present? %>
  		<aside class="alert alert info">
  			<%= notice %>
  		</aside>
  	<% end %>
  	<% if alert.present? %>
  		<aside class="alert alert-danger">
  			<%= alert %>
  		</aside>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/machines/_pager.html.erb
<nav>
	<ul class="pager">
	<% if page > 0 %>
		<li class="previous">
		<%= link_to "&larr; Previous".html_safe, machines_path(keywords: keywords, page: page - 1), title: "Previous Page" %>
		</li>
	<% end %>
	
		<li class="next">
		<%= link_to "Next &rarr;".html_safe, machines_path(keywords: keywords, page: page + 1), title: "Next Page" %>
		</li>
	</ul>
</nav>

app/views/machines/index.html.erb
<HEADER>
	<h1 Class="h2">Machine Search</h1>
</HEADER>

<section class="search-form">
	<%= form_for :machines, method: :get do |f| %>
		<div class="input-group input-group-lg">
			<%= label_tag :keywords, nil, class: "sr-only" %>
			<%= text_field_tag :keywords, nil, placeholder: "machine Name, ip address", class: "form-control input-lg" %>
				<span class="input-group-btn">
					<%= submit_tag "Find Machines", class: "btn btn-primary btn-lg" %>
				</span>
		</div>
	<% end %>
</section>

<section class="search-results">
<header>
	<h1 class="h3">Results</h1>
</header>
<% if @machines.present? %>
	<%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
<% end %>
<ol class="list-group">
	<% @machines.each do |machine| %>
		<li class="list-group-item clearfix">
			<h3 class="pull-right">
				<small class="text-uppercase">Added</small> <%= l machine.created_at.to_date %>
			</h3>
			<h2 class="h3">
				<%= machine.machine_name %> <%= machine.ip_address %>
			<small><%= machine.mac_address %></small>
		</h2>
			<h5><%= machine.machine_serialno %></h5>
			
		</li>
	<% end %>
</ol>
<% if @machines.present? %>
	<%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
<% end %>
</section>


<!-- </header>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Machine Name</th>
			<th>Ip Address</th>
			<th>MAC Address</th>
			<th>Make</th>
			<th>Model</th>
			<th>Serial Number</th>
		</tr>
	</thead>
<tbody>
	<% @machines.each do |machine| %>
	<tr>
		<td><%= machine.machine_name %></td>
		<td><%= machine.ip_address %></td>
		<td><%= machine.mac_address %></td>
		<td><%= machine.machine_make %></td>
		<td><%= machine.machine_model %></td>
		<td><%= machine.machine_serialno %></td>
	</tr>
	<% end %>
</tbody>
</table>
</section> -->